image: "node:latest"

stages:
  - install_dependencies
  - deploy_migrations

cache:
  paths:
    -node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - npm install

deploy_migrations:
  stage: deploy_migrations
  when: manual
  script:
    - npm run migrations


