image: "node:latest"

stages:
  - install_dependencies
  - deploy_migrations

install_dependencies_job:
  stage: install_dependencies
  script:
    - npm install

deploy_migrations:
  stage: deploy_migrations
  when: manual
  script:
    - npm run migrations


