name: Publish migrations

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install knex and publish migrations
        env:
          DB_URL: ${{ secrets.DB_URL }}
          NODE_ENV: production
        run: npm ci && npm run migrations
