name: Publish migrations

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      env:
        DB_URL: ${{ secrets.DB_URL }} 
      with:
        node-version: ${{ matrix.node-version }}
    - name: install knex and publish migrations
      run: |
        npm ci
        npm run migrations
